# Reinforcement learning configuration for SAC
algorithm_name: "SAC"
set_initial_obs: true
simulation_parameters_file: "Settings/simulation_parameters.yaml"

# Environment settings
max_waypoints: 10
termination_distance: 5.0
action_bounds:
  low: [-250.0, -250.0, -250.0, 2.0]
  high: [250.0, 250.0, 250.0, 20.0]
cost_parameters:
  altitude_weight: 0.01
  power_weight: 0.0001
  noise_weight: 15.0
  completion_weight: 1000.0
  save_costs_in_history: false

# SAC hyperparameters
total_timesteps: 2000 # Total number of timesteps for training
learning_rate: 0.0003 # Learning rate for the optimizer
buffer_size: 50000 # Size of the replay buffer
batch_size: 128 # Batch size for sampling from the replay buffer
gamma: 0.99 # Discount factor for future rewards
tau: 0.005 # Soft update coefficient for target networks
train_freq: 1 # Frequency of training steps
gradient_steps: 1 # Number of gradient steps per training step
ent_coef: "auto" # Entropy coefficient
target_update_interval: 1 # Frequency of target network updates
learning_starts: 1000 # Number of steps before training starts
policy: "MlpPolicy" # Policy architecture
log_interval: 1 # Logging interval
device: "auto" # Device to use for training ("cpu", "cuda", or "auto")
evaluation_episodes: 1 # Number of episodes for evaluation
